import { useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
  RotateCcw,
  MessageCircle,
  Download,
  Award,
  TrendingUp,
  Briefcase,
  GraduationCap,
  Sparkles,
  ChevronRight,
  User,
  Brain,
  Target,
  BookOpen,
} from 'lucide-react';
import prepmateLogo from '@/assets/prepmate-logo.png';
import { AssessmentAnswers } from './CareerAssessment';
import { TraitDimensions } from '@/data/assessmentQuestions';
import { 
  getCareerPathsForClass, 
  calculateCareerScores, 
  getTraitProfileSummary 
} from '@/data/careerGroups';

interface CareerResultsDashboardProps {
  answers: AssessmentAnswers;
  scores: TraitDimensions;
  completedClass: 'after_10th' | 'after_12th_science' | 'after_12th_commerce';
  stream?: string;
  onRetake: () => void;
  onChatWithMentor: () => void;
}

// Trait display configuration
const traitConfig: Record<keyof TraitDimensions, { label: string; icon: string }> = {
  analytical_reasoning: { label: 'Analytical Thinking', icon: '🧮' },
  system_thinking: { label: 'Systems Thinking', icon: '⚙️' },
  people_involvement: { label: 'People-Oriented', icon: '👥' },
  persuasion_influence: { label: 'Influential', icon: '📢' },
  creative_expression: { label: 'Creative', icon: '🎨' },
  visual_thinking: { label: 'Visual Thinker', icon: '👁️' },
  precision_orientation: { label: 'Detail-Focused', icon: '🎯' },
  risk_appetite: { label: 'Risk Comfort', icon: '🎲' },
  learning_depth_tolerance: { label: 'Deep Learner', icon: '📚' },
  ambiguity_tolerance: { label: 'Adaptable', icon: '🌊' },
  execution_drive: { label: 'Action-Oriented', icon: '⚡' },
  planning_drive: { label: 'Strategic Planner', icon: '📋' },
};

export function CareerResultsDashboard({
  answers,
  scores,
  completedClass,
  stream,
  onRetake,
  onChatWithMentor,
}: CareerResultsDashboardProps) {
  // Calculate career matches
  const careerMatches = useMemo(() => {
    const classKey = completedClass === 'after_10th' ? '10th' :
      completedClass === 'after_12th_science' ? '12th_science' : '12th_commerce';
    const careers = getCareerPathsForClass(classKey);
    return calculateCareerScores(scores, careers);
  }, [scores, completedClass]);

  // Get trait profile
  const traitProfile = useMemo(() => getTraitProfileSummary(scores), [scores]);

  // Sort traits by score for display
  const sortedTraits = useMemo(() => {
    return Object.entries(scores)
      .map(([key, value]) => ({
        key: key as keyof TraitDimensions,
        value,
        ...traitConfig[key as keyof TraitDimensions],
      }))
      .sort((a, b) => b.value - a.value);
  }, [scores]);

  // Max score for normalization
  const maxTraitScore = Math.max(...Object.values(scores), 1);

  const topMatch = careerMatches[0];
  const alternatives = careerMatches.slice(1, 4);

  const handleExportPDF = () => {
    const content = `
PrepMate Career Assessment Report
===================================

Assessment Type: ${completedClass === 'after_10th' ? 'After 10th' : completedClass === 'after_12th_science' ? `After 12th Science (${stream})` : 'After 12th Commerce'}

BEHAVIORAL PROFILE
==================
Dominant Traits: ${traitProfile.dominant.join(', ')}
Work Style: ${traitProfile.workStyle}
Learning Style: ${traitProfile.learningStyle}

TOP RECOMMENDATION
==================
${topMatch?.career.name} (${topMatch?.score}% match)
${topMatch?.career.description}

Why this suits you: ${topMatch?.reasons.join(', ')}

ALTERNATIVE PATHS
==================
${alternatives.map((match, i) => `${i + 1}. ${match.career.name} (${match.score}% match)`).join('\n')}

---
Generated by PrepMate - Shape Your Career Path
This is a guidance tool. Please discuss with counselors before making decisions.
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'PrepMate_Career_Report.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5 p-4 md:p-8">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
          <div className="flex items-center gap-4">
            <img src={prepmateLogo} alt="PrepMate" className="h-12 w-auto" />
            <div>
              <h1 className="text-2xl md:text-3xl font-bold text-foreground">
                Your Career Discovery Results
              </h1>
              <p className="text-muted-foreground">
                {completedClass === 'after_10th' ? 'After 10th Assessment' : 
                 completedClass === 'after_12th_science' ? `After 12th Science (${stream})` : 
                 'After 12th Commerce Assessment'}
              </p>
            </div>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button variant="outline" size="sm" onClick={handleExportPDF}>
              <Download className="h-4 w-4 mr-2" />
              Export
            </Button>
            <Button variant="outline" size="sm" onClick={onRetake}>
              <RotateCcw className="h-4 w-4 mr-2" />
              Retake
            </Button>
          </div>
        </div>

        {/* Main Grid */}
        <div className="grid gap-6 md:grid-cols-3">
          {/* Left Column - Behavioral Profile */}
          <div className="md:col-span-1 space-y-6">
            {/* Profile Summary Card */}
            <Card className="border-border/50 bg-card">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <User className="h-5 w-5 text-primary" />
                  Your Profile
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <p className="text-sm text-muted-foreground mb-2">Dominant Traits</p>
                  <div className="flex flex-wrap gap-2">
                    {traitProfile.dominant.map((trait, i) => (
                      <Badge key={i} variant="secondary" className="bg-primary/10 text-primary">
                        {trait}
                      </Badge>
                    ))}
                  </div>
                </div>
                
                <Separator />
                
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <p className="text-xs text-muted-foreground mb-1">Work Style</p>
                    <p className="text-sm font-medium text-foreground">{traitProfile.workStyle}</p>
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground mb-1">Learning Style</p>
                    <p className="text-sm font-medium text-foreground">{traitProfile.learningStyle}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Trait Breakdown */}
            <Card className="border-border/50 bg-card">
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Brain className="h-5 w-5 text-primary" />
                  Trait Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {sortedTraits.slice(0, 6).map((trait) => (
                  <div key={trait.key} className="space-y-1">
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-foreground flex items-center gap-2">
                        <span>{trait.icon}</span>
                        {trait.label}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        {Math.round((trait.value / maxTraitScore) * 100)}%
                      </span>
                    </div>
                    <Progress 
                      value={(trait.value / maxTraitScore) * 100} 
                      className="h-2 bg-muted"
                    />
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>

          {/* Right Column - Career Results */}
          <div className="md:col-span-2 space-y-6">
            {/* Top Match Card */}
            {topMatch && (
              <Card className="border-primary/30 bg-gradient-to-r from-primary/5 to-accent/5">
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <div>
                      <Badge className="bg-primary/20 text-primary border-primary/30 mb-2">
                        <Award className="h-3 w-3 mr-1" />
                        Best Match
                      </Badge>
                      <CardTitle className="text-2xl text-foreground">
                        {topMatch.career.name}
                      </CardTitle>
                      <CardDescription className="mt-2">
                        {topMatch.career.description}
                      </CardDescription>
                    </div>
                    <div className="text-right">
                      <div className="text-4xl font-bold text-primary">{topMatch.score}%</div>
                      <p className="text-xs text-muted-foreground">Compatibility</p>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  {/* Why This Suits You */}
                  <div>
                    <h4 className="text-sm font-medium text-foreground mb-2 flex items-center gap-2">
                      <Sparkles className="h-4 w-4 text-primary" />
                      Why This Suits You
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {topMatch.reasons.map((reason, i) => (
                        <Badge key={i} variant="outline" className="bg-card">
                          {reason}
                        </Badge>
                      ))}
                    </div>
                  </div>

                  {/* Quick Info */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4 pt-4 border-t border-border/50">
                    <div>
                      <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                        <TrendingUp className="h-3 w-3" /> Growth
                      </p>
                      <p className="text-sm font-medium text-foreground">{topMatch.career.growthOutlook}</p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                        <Briefcase className="h-3 w-3" /> Environment
                      </p>
                      <p className="text-sm font-medium text-foreground line-clamp-1">
                        {topMatch.career.workEnvironment.split(',')[0]}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                        <GraduationCap className="h-3 w-3" /> Path
                      </p>
                      <p className="text-sm font-medium text-foreground line-clamp-1">
                        {topMatch.career.educationPath[0]}
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                        💰 Salary Range
                      </p>
                      <p className="text-sm font-medium text-foreground">{topMatch.career.salaryRange}</p>
                    </div>
                  </div>

                  {/* Typical Day */}
                  <div className="bg-muted/30 rounded-lg p-4 border border-border/50">
                    <h4 className="text-sm font-medium text-foreground mb-2 flex items-center gap-2">
                      <BookOpen className="h-4 w-4" />
                      A Typical Day
                    </h4>
                    <p className="text-sm text-muted-foreground">{topMatch.career.typicalDay}</p>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Alternative Paths */}
            <Card className="border-border/50 bg-card">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Target className="h-5 w-5 text-primary" />
                  Alternative Paths to Explore
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  {alternatives.map((match) => (
                    <div
                      key={match.career.id}
                      className="flex items-center justify-between p-4 rounded-xl border border-border/50 bg-muted/20 hover:bg-muted/40 transition-colors"
                    >
                      <div className="flex items-center gap-4">
                        <div className="text-2xl">{match.career.icon}</div>
                        <div>
                          <h4 className="font-medium text-foreground">{match.career.name}</h4>
                          <p className="text-sm text-muted-foreground line-clamp-1">
                            {match.career.category}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <div className="text-right">
                          <div className="text-xl font-bold text-foreground">{match.score}%</div>
                          <p className="text-xs text-muted-foreground">Match</p>
                        </div>
                        <ChevronRight className="h-5 w-5 text-muted-foreground" />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Chat CTA */}
            <Card className="border-primary/30 bg-gradient-to-r from-primary/10 to-accent/10">
              <CardContent className="p-6">
                <div className="flex flex-col md:flex-row items-center justify-between gap-4">
                  <div>
                    <h3 className="text-lg font-semibold text-foreground mb-1">
                      Have Questions? Talk to Your AI Mentor
                    </h3>
                    <p className="text-muted-foreground text-sm">
                      Get personalized guidance on education paths, entrance exams, and career planning
                    </p>
                  </div>
                  <Button onClick={onChatWithMentor} className="bg-primary hover:bg-primary/90">
                    <MessageCircle className="h-4 w-4 mr-2" />
                    Chat with Mentor
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="mt-8 text-center text-sm text-muted-foreground">
          <p>
            This assessment provides guidance based on behavioral analysis. 
            Please discuss results with parents, teachers, and career counselors before making decisions.
          </p>
        </div>
      </div>
    </div>
  );
}
