import { useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import {
  RotateCcw,
  MessageCircle,
  Download,
  Award,
  TrendingUp,
  Briefcase,
  GraduationCap,
  Sparkles,
  ChevronRight,
  User,
  Brain,
  Target,
  BookOpen,
  Clock,
  MapPin,
  Rocket,
  Star,
  Zap,
} from 'lucide-react';
import { AssessmentAnswers } from './CareerAssessment';
import { TraitDimensions } from '@/data/assessmentQuestions';
import { 
  getCareerPathsForClass, 
  calculateCareerScores, 
  getTraitProfileSummary 
} from '@/data/careerGroups';

interface CareerResultsDashboardProps {
  answers: AssessmentAnswers;
  scores: TraitDimensions;
  completedClass: 'after_10th' | 'after_12th_science' | 'after_12th_commerce';
  stream?: string;
  onRetake: () => void;
  onChatWithMentor: () => void;
}

// Trait display configuration
const traitConfig: Record<keyof TraitDimensions, { label: string; icon: string; color: string }> = {
  analytical_reasoning: { label: 'Analytical Thinking', icon: '🧮', color: 'from-primary to-info' },
  system_thinking: { label: 'Systems Thinking', icon: '⚙️', color: 'from-info to-primary' },
  people_involvement: { label: 'People-Oriented', icon: '👥', color: 'from-success to-info' },
  persuasion_influence: { label: 'Influential', icon: '📢', color: 'from-accent to-warning' },
  creative_expression: { label: 'Creative', icon: '🎨', color: 'from-accent to-destructive' },
  visual_thinking: { label: 'Visual Thinker', icon: '👁️', color: 'from-info to-accent' },
  precision_orientation: { label: 'Detail-Focused', icon: '🎯', color: 'from-primary to-success' },
  risk_appetite: { label: 'Risk Comfort', icon: '🎲', color: 'from-warning to-destructive' },
  learning_depth_tolerance: { label: 'Deep Learner', icon: '📚', color: 'from-primary to-info' },
  ambiguity_tolerance: { label: 'Adaptable', icon: '🌊', color: 'from-info to-success' },
  execution_drive: { label: 'Action-Oriented', icon: '⚡', color: 'from-accent to-success' },
  planning_drive: { label: 'Strategic Planner', icon: '📋', color: 'from-info to-primary' },
};

export function CareerResultsDashboard({
  answers,
  scores,
  completedClass,
  stream,
  onRetake,
  onChatWithMentor,
}: CareerResultsDashboardProps) {
  // Calculate career matches
  const careerMatches = useMemo(() => {
    const classKey = completedClass === 'after_10th' ? '10th' :
      completedClass === 'after_12th_science' ? '12th_science' : '12th_commerce';
    const careers = getCareerPathsForClass(classKey);
    return calculateCareerScores(scores, careers);
  }, [scores, completedClass]);

  // Get trait profile
  const traitProfile = useMemo(() => getTraitProfileSummary(scores), [scores]);

  // Sort traits by score for display
  const sortedTraits = useMemo(() => {
    return Object.entries(scores)
      .map(([key, value]) => ({
        key: key as keyof TraitDimensions,
        value,
        ...traitConfig[key as keyof TraitDimensions],
      }))
      .sort((a, b) => b.value - a.value);
  }, [scores]);

  // Max score for normalization
  const maxTraitScore = Math.max(...Object.values(scores), 1);

  const topMatch = careerMatches[0];
  const alternatives = careerMatches.slice(1, 4);

  const handleExportPDF = () => {
    const content = `
PrepMate Career Assessment Report
===================================

Assessment Type: ${completedClass === 'after_10th' ? 'After 10th' : completedClass === 'after_12th_science' ? `After 12th Science (${stream})` : 'After 12th Commerce'}

BEHAVIORAL PROFILE
==================
Dominant Traits: ${traitProfile.dominant.join(', ')}
Work Style: ${traitProfile.workStyle}
Learning Style: ${traitProfile.learningStyle}

TOP RECOMMENDED CAREER PATH
===========================
${topMatch?.career.name} (${topMatch?.score}% match)
${topMatch?.career.description}

Why this suits you: ${topMatch?.reasons.join(', ')}

Education Path: ${topMatch?.career.educationPath.join(' → ')}
Salary Range: ${topMatch?.career.salaryRange}
Growth Outlook: ${topMatch?.career.growthOutlook}

ALTERNATIVE CAREER PATHS
========================
${alternatives.map((match, i) => `${i + 1}. ${match.career.name} (${match.score}% match)
   - ${match.career.description}
   - Education: ${match.career.educationPath[0]}`).join('\n\n')}

---
Generated by PrepMate - Shape Your Career Path
This is a guidance tool. Please discuss with counselors before making decisions.
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'PrepMate_Career_Report.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-success';
    if (score >= 60) return 'text-info';
    if (score >= 40) return 'text-warning';
    return 'text-muted-foreground';
  };

  const getScoreBg = (score: number) => {
    if (score >= 80) return 'bg-success/10 border-success/30';
    if (score >= 60) return 'bg-info/10 border-info/30';
    if (score >= 40) return 'bg-warning/10 border-warning/30';
    return 'bg-muted border-border';
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5 p-4 md:p-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
          <div className="fade-in-up">
            <div className="flex items-center gap-2 mb-2">
              <div className="p-2 rounded-xl bg-primary/10">
                <Rocket className="h-6 w-6 text-primary" />
              </div>
              <Badge variant="outline" className="bg-success/10 text-success border-success/30">
                Assessment Complete
              </Badge>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-foreground">
              Your Career Discovery Results
            </h1>
            <p className="text-muted-foreground mt-1">
              {completedClass === 'after_10th' ? 'After 10th Assessment' : 
               completedClass === 'after_12th_science' ? `After 12th Science (${stream})` : 
               'After 12th Commerce Assessment'}
            </p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button variant="outline" size="sm" onClick={handleExportPDF} className="hover:bg-primary/5">
              <Download className="h-4 w-4 mr-2" />
              Export Report
            </Button>
            <Button variant="outline" size="sm" onClick={onRetake} className="hover:bg-destructive/5">
              <RotateCcw className="h-4 w-4 mr-2" />
              Retake
            </Button>
          </div>
        </div>

        {/* Top Match Hero Card */}
        {topMatch && (
          <Card className="mb-8 border-2 border-primary/30 bg-gradient-to-br from-primary/5 via-card to-accent/5 overflow-hidden fade-in-up shadow-xl">
            <div className="absolute inset-0 bg-gradient-to-r from-primary/5 to-transparent" />
            <CardContent className="p-6 md:p-8 relative">
              <div className="flex flex-col lg:flex-row gap-6">
                {/* Left - Main Info */}
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="text-5xl">{topMatch.career.icon}</div>
                    <div>
                      <Badge className="bg-gradient-to-r from-primary to-accent text-primary-foreground border-0 mb-2">
                        <Star className="h-3 w-3 mr-1 fill-current" />
                        Top Match
                      </Badge>
                      <h2 className="text-2xl md:text-3xl font-bold text-foreground">
                        {topMatch.career.name}
                      </h2>
                    </div>
                  </div>
                  
                  <p className="text-muted-foreground text-lg mb-4">
                    {topMatch.career.description}
                  </p>

                  {/* Why This Suits You */}
                  <div className="mb-4">
                    <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
                      <Sparkles className="h-4 w-4 text-accent" />
                      Why This Career Suits You
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {topMatch.reasons.map((reason, i) => (
                        <Badge key={i} variant="secondary" className="bg-primary/10 text-primary border-primary/20">
                          {reason}
                        </Badge>
                      ))}
                    </div>
                  </div>

                  {/* Quick Stats */}
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    <div className="p-3 rounded-xl bg-card/80 border border-border/50">
                      <div className="flex items-center gap-2 text-muted-foreground mb-1">
                        <TrendingUp className="h-4 w-4" />
                        <span className="text-xs font-medium">Growth</span>
                      </div>
                      <p className="text-sm font-semibold text-success">{topMatch.career.growthOutlook}</p>
                    </div>
                    <div className="p-3 rounded-xl bg-card/80 border border-border/50">
                      <div className="flex items-center gap-2 text-muted-foreground mb-1">
                        <Briefcase className="h-4 w-4" />
                        <span className="text-xs font-medium">Environment</span>
                      </div>
                      <p className="text-sm font-semibold text-foreground line-clamp-1">
                        {topMatch.career.workEnvironment.split(',')[0]}
                      </p>
                    </div>
                    <div className="p-3 rounded-xl bg-card/80 border border-border/50">
                      <div className="flex items-center gap-2 text-muted-foreground mb-1">
                        <span className="text-sm">💰</span>
                        <span className="text-xs font-medium">Salary</span>
                      </div>
                      <p className="text-sm font-semibold text-foreground">{topMatch.career.salaryRange}</p>
                    </div>
                    <div className="p-3 rounded-xl bg-card/80 border border-border/50">
                      <div className="flex items-center gap-2 text-muted-foreground mb-1">
                        <GraduationCap className="h-4 w-4" />
                        <span className="text-xs font-medium">Duration</span>
                      </div>
                      <p className="text-sm font-semibold text-foreground">{topMatch.career.educationPath.length} stages</p>
                    </div>
                  </div>
                </div>

                {/* Right - Score Circle */}
                <div className="lg:w-48 flex flex-col items-center justify-center">
                  <div className="relative w-40 h-40">
                    <svg className="w-full h-full transform -rotate-90">
                      <circle
                        cx="80"
                        cy="80"
                        r="70"
                        fill="none"
                        stroke="hsl(var(--muted))"
                        strokeWidth="12"
                      />
                      <circle
                        cx="80"
                        cy="80"
                        r="70"
                        fill="none"
                        stroke="hsl(var(--primary))"
                        strokeWidth="12"
                        strokeLinecap="round"
                        strokeDasharray={`${topMatch.score * 4.4} 440`}
                        className="transition-all duration-1000 ease-out"
                      />
                    </svg>
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-4xl font-bold text-primary">{topMatch.score}%</span>
                      <span className="text-xs text-muted-foreground">Match Score</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* Education Path */}
              <div className="mt-6 pt-6 border-t border-border/50">
                <h4 className="text-sm font-semibold text-foreground mb-3 flex items-center gap-2">
                  <GraduationCap className="h-4 w-4 text-primary" />
                  Your Education Journey
                </h4>
                <div className="flex flex-wrap items-center gap-2">
                  {topMatch.career.educationPath.map((step, i) => (
                    <div key={i} className="flex items-center gap-2">
                      <div className="px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-sm font-medium text-foreground">
                        {step}
                      </div>
                      {i < topMatch.career.educationPath.length - 1 && (
                        <ChevronRight className="h-4 w-4 text-muted-foreground" />
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Typical Day */}
              <div className="mt-6 p-4 rounded-xl bg-muted/50 border border-border/50">
                <h4 className="text-sm font-semibold text-foreground mb-2 flex items-center gap-2">
                  <Clock className="h-4 w-4 text-info" />
                  A Typical Day in This Career
                </h4>
                <p className="text-sm text-muted-foreground">{topMatch.career.typicalDay}</p>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Main Grid */}
        <div className="grid gap-6 lg:grid-cols-3">
          {/* Left Column - Behavioral Profile */}
          <div className="space-y-6">
            {/* Profile Summary Card */}
            <Card className="border-border/50 bg-card overflow-hidden card-interactive fade-in-up" style={{ animationDelay: '100ms' }}>
              <CardHeader className="pb-3 bg-gradient-to-r from-primary/5 to-transparent">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <div className="p-2 rounded-lg bg-primary/10">
                    <User className="h-5 w-5 text-primary" />
                  </div>
                  Your Behavioral Profile
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <p className="text-sm text-muted-foreground mb-2">Top Strengths</p>
                  <div className="flex flex-wrap gap-2">
                    {traitProfile.dominant.map((trait, i) => (
                      <Badge key={i} className="bg-gradient-to-r from-primary/10 to-accent/10 text-primary border-primary/20">
                        <Zap className="h-3 w-3 mr-1" />
                        {trait}
                      </Badge>
                    ))}
                  </div>
                </div>
                
                <Separator />
                
                <div className="grid gap-4">
                  <div className="p-3 rounded-xl bg-muted/50">
                    <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <Briefcase className="h-3 w-3" /> Work Style
                    </p>
                    <p className="text-sm font-semibold text-foreground">{traitProfile.workStyle}</p>
                  </div>
                  <div className="p-3 rounded-xl bg-muted/50">
                    <p className="text-xs text-muted-foreground mb-1 flex items-center gap-1">
                      <BookOpen className="h-3 w-3" /> Learning Style
                    </p>
                    <p className="text-sm font-semibold text-foreground">{traitProfile.learningStyle}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Trait Breakdown */}
            <Card className="border-border/50 bg-card card-interactive fade-in-up" style={{ animationDelay: '200ms' }}>
              <CardHeader className="pb-3">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <div className="p-2 rounded-lg bg-info/10">
                    <Brain className="h-5 w-5 text-info" />
                  </div>
                  Trait Analysis
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {sortedTraits.slice(0, 6).map((trait, i) => (
                  <div key={trait.key} className="space-y-2" style={{ animationDelay: `${i * 50}ms` }}>
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-foreground flex items-center gap-2">
                        <span className="text-lg">{trait.icon}</span>
                        {trait.label}
                      </span>
                      <span className={`text-sm font-bold ${getScoreColor(Math.round((trait.value / maxTraitScore) * 100))}`}>
                        {Math.round((trait.value / maxTraitScore) * 100)}%
                      </span>
                    </div>
                    <div className="h-2.5 bg-muted rounded-full overflow-hidden">
                      <div 
                        className={`h-full rounded-full bg-gradient-to-r ${trait.color} transition-all duration-700 ease-out`}
                        style={{ width: `${(trait.value / maxTraitScore) * 100}%` }}
                      />
                    </div>
                  </div>
                ))}
              </CardContent>
            </Card>
          </div>

          {/* Right Column - Career Paths */}
          <div className="lg:col-span-2 space-y-6">
            {/* Alternative Career Paths */}
            <Card className="border-border/50 bg-card fade-in-up" style={{ animationDelay: '300ms' }}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <div className="p-2 rounded-lg bg-accent/10">
                    <Target className="h-5 w-5 text-accent" />
                  </div>
                  Other Career Paths For You
                </CardTitle>
                <CardDescription>
                  Explore these alternative paths that also match your behavioral profile
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  {alternatives.map((match, i) => (
                    <div
                      key={match.career.id}
                      className={`flex items-start gap-4 p-5 rounded-2xl border-2 ${getScoreBg(match.score)} transition-all duration-300 hover:shadow-lg hover:scale-[1.01] cursor-pointer`}
                      style={{ animationDelay: `${(i + 4) * 100}ms` }}
                    >
                      <div className="text-4xl p-3 rounded-xl bg-card shadow-sm">{match.career.icon}</div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between gap-4">
                          <div>
                            <h4 className="font-bold text-lg text-foreground mb-1">{match.career.name}</h4>
                            <p className="text-sm text-muted-foreground line-clamp-2 mb-3">
                              {match.career.description}
                            </p>
                          </div>
                          <div className="text-right shrink-0">
                            <div className={`text-2xl font-bold ${getScoreColor(match.score)}`}>
                              {match.score}%
                            </div>
                            <p className="text-xs text-muted-foreground">Match</p>
                          </div>
                        </div>
                        
                        {/* Career details */}
                        <div className="flex flex-wrap gap-2">
                          <Badge variant="outline" className="bg-card">
                            <TrendingUp className="h-3 w-3 mr-1" />
                            {match.career.growthOutlook}
                          </Badge>
                          <Badge variant="outline" className="bg-card">
                            💰 {match.career.salaryRange}
                          </Badge>
                          <Badge variant="outline" className="bg-card">
                            <GraduationCap className="h-3 w-3 mr-1" />
                            {match.career.educationPath[0]}
                          </Badge>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Chat CTA */}
            <Card className="border-2 border-primary/30 bg-gradient-to-r from-primary/10 via-card to-accent/10 overflow-hidden fade-in-up" style={{ animationDelay: '500ms' }}>
              <CardContent className="p-6 md:p-8">
                <div className="flex flex-col md:flex-row items-center justify-between gap-6">
                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded-2xl bg-primary/20 shrink-0">
                      <MessageCircle className="h-8 w-8 text-primary" />
                    </div>
                    <div>
                      <h3 className="text-xl font-bold text-foreground mb-1">
                        Need Career Guidance?
                      </h3>
                      <p className="text-muted-foreground">
                        Chat with your AI Career Mentor for personalized advice on education paths, entrance exams, and career planning.
                      </p>
                    </div>
                  </div>
                  <Button 
                    onClick={onChatWithMentor} 
                    size="lg"
                    className="bg-primary hover:bg-primary/90 shadow-lg hover:shadow-xl transition-all shrink-0"
                  >
                    <MessageCircle className="h-5 w-5 mr-2" />
                    Chat with AI Mentor
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="mt-8 text-center p-4 rounded-xl bg-muted/50 border border-border/50">
          <p className="text-sm text-muted-foreground">
            This assessment provides guidance based on behavioral analysis. 
            Please discuss results with parents, teachers, and career counselors before making important decisions.
          </p>
        </div>
      </div>
    </div>
  );
}
